services:
  - type: web
    name: chatbot-assistant-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
